services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    # ports:
    #   - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    # env_file:
    #   - .env
    environment: # Override with environment variables/env file
      - DB_NAME=db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres:
